# Generated by Django 3.0.5 on 2020-04-14 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biddingtype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Typename', models.TextField()),
                ('TypeDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupBidding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ActualAmount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('biddingAmount', models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True)),
                ('selectedName', models.TextField(null=True)),
                ('SelectedMobileNumber', models.BigIntegerField(null=True)),
                ('Cyclenumber', models.IntegerField(default=0, null=True)),
                ('IsSelected', models.IntegerField(default=0)),
                ('BiddingStatus', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('groupname', models.TextField(max_length=30, null=True)),
                ('startDate', models.DateField(max_length=12, null=True)),
                ('usercount', models.IntegerField(null=True)),
                ('isActive', models.IntegerField(default=1)),
                ('AmountPerUser', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sarkriGhata', models.DecimalField(decimal_places=2, max_digits=8)),
                ('groupbiddingtype', models.IntegerField()),
                ('groupStatus', models.IntegerField(default=5)),
                ('biddingdate', models.DateField(max_length=12, null=True)),
                ('biddingflag', models.IntegerField(default=0)),
                ('biddgingCycle', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('createBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DateofBirth', models.DateField(max_length=12, null=True)),
                ('AlternateMobileNumber', models.BigIntegerField(default=0, null=True)),
                ('ProfilePic', models.ImageField(blank=True, null=True, upload_to='profilepicture')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserDetails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupPaymentHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Mobilenumber', models.BigIntegerField(default=0, null=True)),
                ('UserName', models.TextField()),
                ('ActualAmount', models.DecimalField(decimal_places=2, default=1, max_digits=8, null=True)),
                ('AmountPaid', models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True)),
                ('AmountDue', models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True)),
                ('Cyclenumber', models.IntegerField(default=1, null=True)),
                ('startDate', models.DateField(default=django.utils.timezone.now)),
                ('IsReceived', models.IntegerField(default=0)),
                ('Status', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('GroupBidding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kameteeapp.GroupBidding')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Mobilenumber', models.BigIntegerField()),
                ('UserName', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('UserGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kameteeapp.UserGroup')),
            ],
        ),
        migrations.CreateModel(
            name='GroupBiddingEntries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('biddingAmount', models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True)),
                ('selectedName', models.TextField()),
                ('SelectedMobileNumber', models.BigIntegerField()),
                ('Cyclenumber', models.IntegerField(default=0)),
                ('IsSelected', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('GroupBidding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kameteeapp.GroupBidding')),
            ],
        ),
        migrations.AddField(
            model_name='groupbidding',
            name='UserGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kameteeapp.UserGroup'),
        ),
        migrations.CreateModel(
            name='AmountRecived',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ActualAmount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ActualRecived', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Cyclenumber', models.IntegerField()),
                ('Amountsend', models.IntegerField(default=0)),
                ('RevicerName', models.TextField()),
                ('Recivermobile', models.BigIntegerField()),
                ('RecivedDate', models.DateField(max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('UserGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kameteeapp.UserGroup')),
            ],
        ),
    ]
