# Generated by Django 3.0.5 on 2020-04-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kameteeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('StatusID', models.IntegerField()),
                ('StatusDescritpion', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='groupbiddingtype',
            field=models.IntegerField(default=1),
        ),
    ]
