# Generated by Django 3.0.5 on 2020-05-05 20:49

import Kameteeapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kameteeapp', '0002_auto_20200420_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbiddingentries',
            name='AddedBy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='isAdmin',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grouppaymenthistory',
            name='UserGroup',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Kameteeapp.UserGroup'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='AlternateMobileNumber',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='DateofBirth',
            field=models.DateField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='ProfilePic',
            field=models.ImageField(blank=True, null=True, upload_to=Kameteeapp.models.upload_to),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='biddgingCycle',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
